const PostConstants = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_RECEIVED: "POST_RECEIVED",
  APPEND_POSTS: "APPEND_POSTS",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  NEW_COMMENT: "NEW_COMMENT"
};

module.exports = PostConstants;
